spring.application.name=stormGuard

# --- Gemini ---
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.project-id=stormGuard
# --- Groq (uses OpenAI-compatible starter) ---
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
spring.ai.model.embedding=google-genai

# -- AWS Bedrock --
spring.ai.bedrock.aws.region=${AWS_REGION:us-east-1}
spring.ai.bedrock.aws.access-key=${AWS_ACCESS_KEY_ID}
spring.ai.bedrock.aws.secret-key=${AWS_SECRET_ACCESS_KEY}
spring.ai.bedrock.aws.session-token=${AWS_SESSION_TOKEN}
spring.ai.bedrock.converse.chat.options.model=us.anthropic.claude-sonnet-4-5-20250929-v1:0


## -NWS API's
nws.us.api=https://api.weather.gov/alerts/active

## Geocode API's
geocode.base.url=https://geocoding-api.open-meteo.com/v1/search

## Open-Meteo API's
weather.base.url=https://api.open-meteo.com/v1/forecast

## Mongo DB
spring.data.mongodb.uri=mongodb://localhost:27017/StormGuard
spring.data.mongodb.database=StormGuard
